Fix vscode-extension-release workflow about vsce
`vsce` has been renamed to `@vscode/vsce`.

```
Run npx vsce publish --pat ***

npm WARN exec The following package was not found and will be installed: vsce@2.15.0
npm WARN deprecated vsce@2.15.0: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.
Error: Manifest needs the 'activationEvents' property, given it has a 'main' property.
Error: Process completed with exit code 1.
```